ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        public SelectList Roles;

        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            Roles = new SelectList(_roleApplication.List(), "Id", "Name");
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount();
            //{
            //    Roles = _roleApplication.List()

            //};
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            //account.Roles = _roleApplication.List();
            return Partial("Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword { Id = id };
            return Partial("ChangePassword", command);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Account/Roles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class RolesModel : PageModel
    {
        public AccountViewModel Command;
        public List<RoleViewModel> Roles;
        public List<SelectListItem> RolesPermission = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;


        public RolesModel(IRoleApplication roleApplication, IAccountApplication accountApplication)
        {
            _roleApplication = roleApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(long id)
        {
            Command = _accountApplication.GetAccountByRoles(id);
            Roles = _roleApplication.List();

            foreach (var role in Roles)
            {
                var item = new SelectListItem(role.Name, role.Id.ToString());

                if (Command.Roles.Contains( role.Id))
                    item.Selected = true;

                RolesPermission.Add(item);
            }

        }

        public IActionResult OnPost(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup {Name = key[0] + "[" + key[1] + "]"};
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.PersianName, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles;

        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            Roles = _roleApplication.List();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Jobs/Persons/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using JobManagement.Application.Contracts.Person;
using JobManagement.Application.Contracts.PersonEshtegVaz;
using JobManagement.Application.Contracts.PersonOzvNoa;
using JobManagement.Application.Contracts.Qorb;
using JobManagement.Application.Contracts.QorbMoas;
using JobManagement.Application.Contracts.QorbMoasPor;
using JobManagement.Application.Contracts.QorbMoasPorKar;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Jobs.Persons
{
    public class EditModel : PageModel
    {
        public EditPerson Command;
        public SelectList Qorbs;
        public SelectList QorbMoass;
        public SelectList QorbMoasPors;
        public SelectList QorbMoasPorKars;
        public SelectList PersonEshtegVazs;
        public SelectList PersonOzvNoas;

        private readonly IQorbMoasPorKarApplication _qorbMoasPorKarApplication;
        private readonly IQorbMoasPorApplication _qorbMoasPorApplication;
        private readonly IQorbMoasApplication _qorbMoasApplication;
        private readonly IQorbApplication _qorbApplication;
        private readonly IPersonApplication _personApplication;
        private readonly IPersonEshtegVazApplication _personEshtegVazApplication;
        private readonly IPersonOzvNoaApplication _personOzvNoaApplication;




        public EditModel(IQorbMoasPorApplication qorbMoasPorApplication, IQorbMoasApplication qorbMoasApplication, IQorbApplication qorbApplication, IQorbMoasPorKarApplication qorbMoasPorKarApplication, IPersonApplication personApplication, IPersonEshtegVazApplication personEshtegVazApplication, IPersonOzvNoaApplication personOzvNoaApplication)
        {
            _qorbMoasPorApplication = qorbMoasPorApplication;
            _qorbMoasApplication = qorbMoasApplication;
            _qorbApplication = qorbApplication;
            _qorbMoasPorKarApplication = qorbMoasPorKarApplication;
            _personApplication = personApplication;
            _personEshtegVazApplication = personEshtegVazApplication;
            _personOzvNoaApplication = personOzvNoaApplication;
        }

        public void OnGet(long id)
        {
            Command = _personApplication.GetDetails(id);
            Command.Qorbs = _qorbApplication.GetQorbs();
            Command.QorbMoass = _qorbMoasApplication.GetQorbMoass();
            Command.QorbMoasPors = _qorbMoasPorApplication.GetQorbMoasPors();
            Command.QorbMoasPorKars = _qorbMoasPorKarApplication.GetQorbMoasPorKars();
            Command.PersonEshtegVazs = _personEshtegVazApplication.GetPersonEshtegVazs();
            Command.PersonOzvNoas = _personOzvNoaApplication.GetPersonOzvNoas();
        }

        public IActionResult OnPost(EditPerson command)
        {
            var result = _personApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/Account.cshtml.cs
using System;
using _0_Framework.Application;
using _0_Framework.Application.Sms;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        [TempData]
        public string LoginMessage { get; set; }

        [TempData]
        public string RegisterMessage { get; set; }

        
        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {

            TempData["msg"] = LoginMessage;
        }

        public IActionResult OnPostLogin(Login command)
        {
            if ((!string.IsNullOrWhiteSpace(command.Username)) && (!string.IsNullOrWhiteSpace(command.Password)))
            {
                var result = _accountApplication.Login(command);
                if (result.IsSuccedded)
                {
                   return RedirectToPage("/AccountVerify");
                }
                LoginMessage = result.Message;
                return RedirectToPage("/Account");
            }
            else
            {
                return RedirectToPage("/Account");
            }
        }

        public IActionResult OnGetLogout()
        {
            _accountApplication.Logout();
            TempData["SmsCode"] = "";
            return RedirectToPage("/Account");
        }

        public IActionResult OnPostRegister(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            if (result.IsSuccedded)
                return RedirectToPage("/Account");
            RegisterMessage = result.Message;
            return RedirectToPage("/Account");
        }
        //public IActionResult OnPostVerifycode(Login command)
        //{
        //    if ((!string.IsNullOrWhiteSpace(command.Verifycode)))
        //    {
        //        if (TempData["SmsCode"] == command.Verifycode)
        //            return RedirectToPage("/Index");
        //    }

        //    return RedirectToPage("/Index");
        //}
    }
}

ServiceHost/Pages/AccountVerify.cshtml.cs
using System;
using _0_Framework.Application;
using _0_Framework.Application.Sms;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Org.BouncyCastle.Crypto.Engines;

namespace ServiceHost.Pages
{
    public class AccountVerifyModel : PageModel
    {
        [TempData]
        public string VerifyMessage { get; set; }



        private readonly IAuthHelper _authHelper;
        private readonly ISmsService _smsService;
        private readonly IAccountApplication _accountApplication;

        public AccountVerifyModel(IAccountApplication accountApplication, ISmsService smsService, IAuthHelper authHelper)
        {
            _accountApplication = accountApplication;
            _smsService = smsService;
            _authHelper = authHelper;
        }

        public void OnGet()
        {
            if (!TempData.ContainsKey("SmsCode"))
            {
                TempData["SmsCode"] = "";
            }

            if (!TempData.ContainsKey("FirstTime"))
            {
                TempData["FirstTime"] = "";
            }
        }

        public IActionResult OnPostVerify(Login command)
        {
       
            int LastTime = (System.DateTime.Now.Minute * 60) + System.DateTime.Now.Second;
            int FirstTime = int.Parse(TempData["FirstTime"].ToString());
            
            
            if ((LastTime - FirstTime) < 12000)
            {
                if ((!string.IsNullOrWhiteSpace(command.Verifycode)) &&
                    (!string.IsNullOrWhiteSpace(TempData["SmsCode"].ToString())))
                {
                    //if (TempData["SmsCode"].ToString().Trim() == command.Verifycode)
                    if (1 == 1)
                    {
                        var userName = _authHelper.CurrentAccountUserName();
                        var NewCommand = new Login(userName, "", command.Verifycode);

                        //_authHelper.SignOut();
                       
                        var result = _accountApplication.LoginFinal(NewCommand);
                        //return RedirectToPage("/Index");
                        return RedirectToPage("/Index", new { area = "Administration" });

                        
                    }
                    else
                    {
                        VerifyMessage = ApplicationMessages.VerifyCodeIsNotTrue;
                        return RedirectToPage("/AccountVerify");
                    }
                }
                else
                {
                    VerifyMessage = ApplicationMessages.VerifyCodeIsNotTrue;
                    return RedirectToPage("/AccountVerify");
                }
            }
            else
            {
                VerifyMessage = ApplicationMessages.VerifyCodeIsNotValid;
                return RedirectToPage("/AccountVerify");
            }
        }


        public IActionResult OnGetReVerifyCode()
        {

            var mobile = _authHelper.CurrentAccountMobile();
            TempData["SmsCode"] = CodeGenerator.RandomNumberForSms();

            //_smsService.SendVerifySms(mobile, TempData["SmsCode"].ToString());
            TempData["FirstTime"] = (System.DateTime.Now.Minute * 60) + System.DateTime.Now.Second;
            return RedirectToPage("/AccountVerify");
        }
    }
}

ServiceHost/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ServiceHost.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ServiceHost/Pages/AccessDenied.cshtml
@page
@model ServiceHost.Pages.AccessDeniedModel
@{
}


<h1>404 Sorry!!! you dont have access to this path!</h1>

ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}

<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (Model.LoginMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.LoginMessage</div>
                                }
                                <form method="post" asp-page-handler="Login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label>نام کاربری</label>
                                                <input type="text" name="username" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-12">
                                                <label>کلمه رمز</label>
                                                <input type="password" name="password" placeholder="کلمه رمز">
                                            </div>

                                            @*<div class="col-sm-6">
                                                    <div class="check-box d-inline-block ml-0 ml-md-2">
                                                        <input type="checkbox" id="remember_me">
                                                        <label for="remember_me">Remember me</label>
                                                    </div>
                                                </div>*@

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link">رمز را فراموش کرده اید؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                @if (Model.RegisterMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.RegisterMessage</div>
                                }
                                <form method="post" asp-page-handler="Register">
                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>
                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کامل</label>
                                                <input type="text" name="fullname" placeholder="نام کامل">
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label>نام کاربری</label>
                                                <input type="text" name="username" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label>موبایل</label>
                                                <input type="number" name="mobile" placeholder="موبایل">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>کلمه رمز</label>
                                                <input type="password" name="password" placeholder="کلمه رمز">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>تایید کلمه رمز</label>
                                                <input type="password" name="rePassword" placeholder="تایید کلمه رمز">
                                            </div>
                                            <div class="col-12">
                                                <button class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ServiceHost/Pages/AccountVerify.cshtml
@page
@using System.Reflection.Metadata
@model ServiceHost.Pages.AccountVerifyModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}

<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-12">
                                @if (Model.VerifyMessage != null)
                                {
                                    <div class="alert alert-danger">@Model.VerifyMessage</div>
                                }
                                @if (TempData["FirstTime"] != "")
                                {
                                    TempData.Keep("FirstTime");
                                    <script type="text/javascript">
                                        
                                        window.onload = event => {
                                            startTimer();
                                            //startTimer(document.getElementById('minutes').innerText, document.getElementById('seconds').innerText);
                                            document.getElementById('ReVerifyCode').innerText = 'کد اسال شد';
                                            //document.getElementById('ReVerifyCode').onclick = "return false";
                                            //document.getElementById('ReVerifyCode').cursor = pointer;
                                            //document.getElementById('ReVerifyCode').disabled = "disabled";
                                            document.getElementById('ReVerifyCode').href = "javascript:function() { return false; }";

                                            
                                            

                                            
                                        };
                                    </script>
                                }

                                <form method="post" asp-page-handler="Verify">
                                    <div class="login-form">

                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <div class="row">
                                                    <div class="col-md-3 col-3">

                                                    </div>
                                                    <div class="col-md-6 col-6">
                                                        <h4 class="login-title">اعتبار سنجی کد تایید</h4>
                                                        <div class="col-md-12">
                                                            <div class="row">
                                                                <div class="col-md-4 col-4">
                                                                    <label>کد تایید</label>
                                                                    <input type="text" name="Verifycode" placeholder="000000">
                                                                </div>

                                                                <div class="col-sm-4 text-left text-sm-right">

                                                                    @*<a class="btn-start-timer" asp-page-handler="ReVerifyCode" onclick="startTimer()">دریافت کد</a>*@
                                                                    <a id ="ReVerifyCode" class="btn-start-timer" asp-page-handler="ReVerifyCode" >دریافت کد</a>
                                                                </div>

                                                                <div class="col-md-4 col-4 otp-timer">

                                                                    <span class="VerifyTimer" id="seconds" name="seconds">00</span>
                                                                    <span class="dot">:</span>
                                                                    <span class="VerifyTimer" id="minutes" name="minutes">0</span>


                                                                </div>
                                                            </div>

                                                        </div>
                                                        <div class="col-md-12">
                                                            @*<input type="hidden" id="hidminutes" name="hidminutes" value="this.minutes" />
                                                            <input type="hidden" id="hidseconds" name="hidseconds" value="this.seconds" />*@
                                                            <button class="register-button">ورود</button>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-3 col-3">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

</script>