ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        public SelectList Roles;

        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            Roles = new SelectList(_roleApplication.List(), "Id", "Name");
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount();
            //{
            //    Roles = _roleApplication.List()

            //};
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            //account.Roles = _roleApplication.List();
            return Partial("Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword { Id = id };
            return Partial("ChangePassword", command);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Account/Roles.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class RolesModel : PageModel
    {
        public AccountViewModel Command;
        public List<RoleViewModel> Roles;
        public List<SelectListItem> RolesPermission = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;


        public RolesModel(IRoleApplication roleApplication, IAccountApplication accountApplication)
        {
            _roleApplication = roleApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(long id)
        {
            Command = _accountApplication.GetAccountByRoles(id);
            Roles = _roleApplication.List();

            foreach (var role in Roles)
            {
                var item = new SelectListItem(role.Name, role.Id.ToString());

                if (Command.Roles.Contains( role.Id))
                    item.Selected = true;

                RolesPermission.Add(item);
            }

        }

        public IActionResult OnPost(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup {Name = key[0] + "[" + key[1] + "]"};
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.PersianName, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles;

        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            Roles = _roleApplication.List();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Jobs/Persons/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using JobManagement.Application.Contracts.Person;
using JobManagement.Application.Contracts.PersonEshtegVaz;
using JobManagement.Application.Contracts.PersonOzvNoa;
using JobManagement.Application.Contracts.Qorb;
using JobManagement.Application.Contracts.QorbMoas;
using JobManagement.Application.Contracts.QorbMoasPor;
using JobManagement.Application.Contracts.QorbMoasPorKar;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Jobs.Persons
{
    public class CreateModel : PageModel
    {
        [TempData] public string Message { get; set; }
        public CreatePerson Command;
        public SelectList Qorbs;
        public SelectList QorbMoass;
        public SelectList QorbMoasPors;
        public SelectList QorbMoasPorKars;
        public SelectList PersonEshtegVazs;
        public SelectList PersonOzvNoas;

        private readonly IQorbMoasPorKarApplication _qorbMoasPorKarApplication;
        private readonly IQorbMoasPorApplication _qorbMoasPorApplication;
        private readonly IQorbMoasApplication _qorbMoasApplication;
        private readonly IQorbApplication _qorbApplication;
        private readonly IPersonApplication _personApplication;
        private readonly IPersonEshtegVazApplication _personEshtegVazApplication;
        private readonly IPersonOzvNoaApplication _personOzvNoaApplication;

        public CreateModel(IQorbMoasPorApplication qorbMoasPorApplication, IQorbMoasApplication qorbMoasApplication, IQorbApplication qorbApplication, IQorbMoasPorKarApplication qorbMoasPorKarApplication, IPersonApplication personApplication, IPersonEshtegVazApplication personEshtegVazApplication, IPersonOzvNoaApplication personOzvNoaApplication)
        {
            _qorbMoasPorApplication = qorbMoasPorApplication;
            _qorbMoasApplication = qorbMoasApplication;
            _qorbApplication = qorbApplication;
            _qorbMoasPorKarApplication = qorbMoasPorKarApplication;
            _personApplication = personApplication;
            _personEshtegVazApplication = personEshtegVazApplication;
            _personOzvNoaApplication = personOzvNoaApplication;
        }

        public void OnGet()
        {
            Qorbs = new SelectList(_qorbApplication.GetQorbs(), "Id", "Name");
            QorbMoass = new SelectList(_qorbMoasApplication.GetQorbMoass(), "Id", "Name");
            QorbMoasPors = new SelectList(_qorbMoasPorApplication.GetQorbMoasPors(), "Id", "Name");
            QorbMoasPorKars = new SelectList(_qorbMoasPorKarApplication.GetQorbMoasPorKars(), "Id", "Name");
            PersonEshtegVazs = new SelectList(_personEshtegVazApplication.GetPersonEshtegVazs(), "Id", "Name");
            PersonOzvNoas = new SelectList(_personOzvNoaApplication.GetPersonOzvNoas(), "Id", "Name");
        }
        
        public IActionResult OnPost(CreatePerson command)
        {
            var result = _personApplication.Create(command);
            if (!result.IsSuccedded)
            {
                Message = result.Message;
                return RedirectToPage("Create");
            }
            else
            {
                return RedirectToPage("Index");
            }

            
        }
    }
}

ServiceHost/Areas/Administration/Pages/Jobs/Persons/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using JobManagement.Application.Contracts.Person;
using JobManagement.Application.Contracts.PersonEshtegVaz;
using JobManagement.Application.Contracts.PersonOzvNoa;
using JobManagement.Application.Contracts.Qorb;
using JobManagement.Application.Contracts.QorbMoas;
using JobManagement.Application.Contracts.QorbMoasPor;
using JobManagement.Application.Contracts.QorbMoasPorKar;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Jobs.Persons
{
    public class EditModel : PageModel
    {
        public EditPerson Command;
        public SelectList Qorbs;
        public SelectList QorbMoass;
        public SelectList QorbMoasPors;
        public SelectList QorbMoasPorKars;
        public SelectList PersonEshtegVazs;
        public SelectList PersonOzvNoas;

        private readonly IQorbMoasPorKarApplication _qorbMoasPorKarApplication;
        private readonly IQorbMoasPorApplication _qorbMoasPorApplication;
        private readonly IQorbMoasApplication _qorbMoasApplication;
        private readonly IQorbApplication _qorbApplication;
        private readonly IPersonApplication _personApplication;
        private readonly IPersonEshtegVazApplication _personEshtegVazApplication;
        private readonly IPersonOzvNoaApplication _personOzvNoaApplication;




        public EditModel(IQorbMoasPorApplication qorbMoasPorApplication, IQorbMoasApplication qorbMoasApplication, IQorbApplication qorbApplication, IQorbMoasPorKarApplication qorbMoasPorKarApplication, IPersonApplication personApplication, IPersonEshtegVazApplication personEshtegVazApplication, IPersonOzvNoaApplication personOzvNoaApplication)
        {
            _qorbMoasPorApplication = qorbMoasPorApplication;
            _qorbMoasApplication = qorbMoasApplication;
            _qorbApplication = qorbApplication;
            _qorbMoasPorKarApplication = qorbMoasPorKarApplication;
            _personApplication = personApplication;
            _personEshtegVazApplication = personEshtegVazApplication;
            _personOzvNoaApplication = personOzvNoaApplication;
        }

        public void OnGet(long id)
        {
            Command = _personApplication.GetDetails(id);
            Command.Qorbs = _qorbApplication.GetQorbs();
            Command.QorbMoass = _qorbMoasApplication.GetQorbMoass();
            Command.QorbMoasPors = _qorbMoasPorApplication.GetQorbMoasPors();
            Command.QorbMoasPorKars = _qorbMoasPorKarApplication.GetQorbMoasPorKars();
            Command.PersonEshtegVazs = _personEshtegVazApplication.GetPersonEshtegVazs();
            Command.PersonOzvNoas = _personOzvNoaApplication.GetPersonOzvNoas();
        }

        public IActionResult OnPost(EditPerson command)
        {
            var result = _personApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Systems/QorbMoasPorKars/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using JobManagement.Application.Contracts.Qorb;
using JobManagement.Application.Contracts.QorbMoas;
using JobManagement.Application.Contracts.QorbMoasPor;
using JobManagement.Application.Contracts.QorbMoasPorKar;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Systems.QorbMoasPorKars
{
    public class CreateModel : PageModel
    {
        public CreateQorbMoasPorKar Command;
        public SelectList Qorbs;
        public SelectList QorbMoass;
        public SelectList QorbMoasPors;

        private readonly IQorbMoasPorKarApplication _qorbMoasPorKarApplication;
        private readonly IQorbMoasPorApplication _qorbMoasPorApplication;
        private readonly IQorbMoasApplication _qorbMoasApplication;
        private readonly IQorbApplication _qorbApplication;

        public CreateModel(IQorbMoasPorApplication qorbMoasPorApplication, IQorbMoasApplication qorbMoasApplication, IQorbApplication qorbApplication, IQorbMoasPorKarApplication qorbMoasPorKarApplication)
        {
            _qorbMoasPorApplication = qorbMoasPorApplication;
            _qorbMoasApplication = qorbMoasApplication;
            _qorbApplication = qorbApplication;
            _qorbMoasPorKarApplication = qorbMoasPorKarApplication;
        }

        public void OnGet()
        {
            Qorbs = new SelectList(_qorbApplication.GetQorbs(), "Id", "Name");
            QorbMoass = new SelectList(_qorbMoasApplication.GetQorbMoass(), "Id", "Name");
            QorbMoasPors = new SelectList(_qorbMoasPorApplication.GetQorbMoasPors(), "Id", "Name");
            //QorbMoass = new SelectList(_qorbMoasApplication.GetQorbMoassWithQorb(searchModel.QorbId), "Id", "Name");
            //QorbMoasPors = _qorbMoasPorApplication.Search(searchModel);
        }
        
        public IActionResult OnPost(CreateQorbMoasPorKar command)
        {
            var result = _qorbMoasPorKarApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Account/ChangePassword.cshtml
@model AccountManagement.Application.Contracts.Account.ChangePassword
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">تغییر کلمه رمز</h4>
</div>

<form asp-page="./Index" asp-page-handler="ChangePassword"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">کلمه رمز</label>
                    <input type="password" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label">تکرار کلمه رمز</label>
                    <input type="password" class="form-control" asp-for="RePassword">
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">اعمال تغییر</button>
        </div>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Create.cshtml
@model AccountManagement.Application.Contracts.Account.RegisterAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد کاربر جدید</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">کلمه رمز</label>
                    <input type="text" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
        </div>
        @*<div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select class="form-control" asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                        <option value="0">گروه محصول</option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>*@
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">عکس پروفایل</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش کاربر: @Model.Fullname</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">نام</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">نام کاربری</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">موبایل</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
        </div>
        @*<div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">نقش</label>
                    <select class="form-control" asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                        <option value="0">گروه محصول</option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>*@
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">عکس پروفایل</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml
@page
@using AccountManagement.Configuration.Permissions
@model ServiceHost.Areas.Administration.Pages.Accounts.Account.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت کاربران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a permission="@AccountPermissions.CreateAccount" class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد کاربر جدید</a>
        </p>
    </div>
</div>

<div class="row" permission="@AccountPermissions.SearchAccounts">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در کاربران</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Fullname"></label>
                        <input class="form-control" asp-for="SearchModel.Fullname" placeholder="نام">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Username"></label>
                        <input class="form-control" asp-for="SearchModel.Username" placeholder="نام کاربری">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Mobile"></label>
                        <input class="form-control" asp-for="SearchModel.Mobile" placeholder="موبایل">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.RoleId"></label>
                        <select class="form-control" asp-for="SearchModel.RoleId" asp-items="Model.Roles">
                            <option value="0">نقش ...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv" permission="@AccountPermissions.ListAccounts">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست کاربران (@Model.Accounts.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام</th>
                                    <th>نام کاربری</th>
                                    <th>موبایل</th>
                                    @*<th>نقش</th>*@
                                    <th>تاریخ تولید</th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Accounts)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.ProfilePhoto" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Fullname</td>
                                        <td>@item.Username</td>
                                        <td>@item.Mobile</td>
                                        @*<td>@item.Role</td>*@
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a permission="@AccountPermissions.EditAccount" class="btn btn-warning waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            <a permission="@AccountPermissions.EditAccountRoles" class="btn btn-warning waves-effect waves-light m-b-5" asp-page="Roles" asp-route-id="@item.Id">
                                                <i class="fa fa-edit"></i> نقش ها
                                            </a>
                                            <a permission="@AccountPermissions.ChangePassword" class="btn btn-primary waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "ChangePassword", new { id = item.Id})">
                                                <i class="fa fa-key"></i> تغییر رمز
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}